# Generated by Django 6.1 on 2026-08-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='db_name',
            field=models.CharField(blank=True, default='dvdrental', help_text='База для SQL-проверки', max_length=64),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('sql', 'SQL'), ('python', 'Python')], default='sql', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(help_text='Правильный ответ: SQL-запрос или ожидаемый stdout для Python'),
        ),
    ]
