# Generated by Django 6.1 on 2026-08-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_db_name_task_task_type_alter_task_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_write',
            field=models.BooleanField(default=False, help_text='Разрешить UPDATE/INSERT/DELETE (для транзакционных задач)'),
        ),
    ]
