# Generated by Django 6.1 on 2026-08-28 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_allow_write'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='hint',
            field=models.TextField(blank=True, help_text='Подсказка (покупается за монеты)'),
        ),
        migrations.AddField(
            model_name='task',
            name='hint_price',
            field=models.PositiveIntegerField(default=0, help_text='Цена подсказки в монетах'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward',
            field=models.PositiveIntegerField(default=5, help_text='Монеты за решение задачи'),
        ),
        migrations.CreateModel(
            name='HintPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_purchases', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'task')},
            },
        ),
    ]
