# Generated by Django 6.1 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_hint_task_hint_price_task_reward_hintpurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_level_test',
            field=models.BooleanField(default=False, help_text='Тест уровня: решающий переходит на следующий уровень'),
        ),
        migrations.AddField(
            model_name='task',
            name='required_level',
            field=models.PositiveIntegerField(default=1, help_text='Минимальный уровень для решения (1-5)'),
        ),
    ]
