# Generated by Django 6.1 on 2026-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_is_level_test_task_required_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tables',
            field=models.CharField(blank=True, help_text='Таблицы для задачи (через запятую)', max_length=200),
        ),
    ]
