# Generated by Django 6.1 on 2026-08-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='required_tokens',
            field=models.CharField(blank=True, help_text='Обязательные элементы в коде (через запятую)', max_length=200),
        ),
    ]
