# Generated by Django 6.1 on 2026-08-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_required_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reference_solution',
            field=models.TextField(blank=True, help_text='Эталонное решение (Python) для сверки вывода ученика'),
        ),
    ]
