# Generated by Django 6.1 on 2026-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_reference_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('sql', 'SQL'), ('python', 'Python'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'JavaScript')], default='sql', max_length=10),
        ),
    ]
